config/routes.rb
Rails.application.routes.draw do
  resources :properties
  # Devise
  devise_for :users,  controllers: { registrations: 'registrations' },
                      path: '',
                      path_names: { sign_in: 'login',
                                    sign_out: 'logout',
                                    sign_up: 'register' }

  # Contacts
  resources :contacts, only: %i[new create]

  # Paginas estaticas
  get '/home', to: 'pages#home'
  get '/terms', to: 'pages#terms'
  root "pages#home"
end

app/models/property.rb
# == Schema Information
#
# Table name: properties
#
#  id               :bigint           not null, primary key
#  user_id          :bigint           not null
#  type_offer_id    :bigint           not null
#  type_property_id :bigint           not null
#  description      :text
#  area             :integer
#  price            :decimal(, )
#  created_at       :datetime         not null
#  updated_at       :datetime         not null
#
class Property < ApplicationRecord
  # Relaciones
  belongs_to :user
  belongs_to :type_offer
  belongs_to :type_property
  # Relaciones
  has_many :property_features, dependent: :destroy
  has_many :features, through: :property_features

  # Validaciones
  validates :description, presence: true
  validates :area, presence: true
  validates :price, presence: true
end

app/controllers/properties_controller.rb
class PropertiesController < ApplicationController
  before_action :set_property, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: %i[ index show ]

  # GET /properties or /properties.json
  def index
    # @properties = Property.all
    @pagy, @properties = pagy(Property.all)
  end

  # GET /properties/1 or /properties/1.json
  def show
  end

  # GET /properties/new
  def new
    @property = current_user.properties.build
  end

  # GET /properties/1/edit
  def edit
  end

  # POST /properties or /properties.json
  def create
    @property = current_user.properties.build(property_params)

    respond_to do |format|
      if @property.save
        format.html { redirect_to property_url(@property), notice: "Property was successfully created." }
        format.json { render :show, status: :created, location: @property }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /properties/1 or /properties/1.json
  def update
    respond_to do |format|
      if @property.update(property_params)
        format.html { redirect_to property_url(@property), notice: "Property was successfully updated." }
        format.json { render :show, status: :ok, location: @property }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @property.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /properties/1 or /properties/1.json
  def destroy
    @property.destroy!

    respond_to do |format|
      format.html { redirect_to properties_url, notice: "Property was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_property
      @property = Property.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def property_params
      params.require(:property).permit(:user_id, :type_offer_id, :type_property_id, :description, :area, :price, feature_ids: [])
    end
end

app/helpers/properties_helper.rb
module PropertiesHelper
end

app/views/properties/_form.html.erb
<%= form_with(model: property) do |form| %>
  <% if property.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(property.errors.count, "error") %> prohibited this property from being saved:</h2>

      <ul>
        <% property.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :user_id, style: "display: block" %>
    <%= form.collection_select :user_id, User.all, :id, :name %>
  </div>

  <div>
    <%= form.label :type_offer_id, style: "display: block" %>
    <%= form.collection_select :type_offer_id, TypeOffer.all, :id, :name %>
  </div>

  <div>
    <%= form.label :type_property_id, style: "display: block" %>
    <%= form.collection_select :type_property_id, TypeProperty.all, :id, :name %>
  </div>

  <div>
    <%= form.label :features, style: "display: block" %>
    <%= form.collection_check_boxes :feature_ids, Feature.all, :id, :name %>
  </div>

  <div>
    <%= form.label :description, style: "display: block" %>
    <%= form.text_area :description, required: true %>
  </div>

  <div>
    <%= form.label :area, style: "display: block" %>
    <%= form.number_field :area, required: true %>
  </div>

  <div>
    <%= form.label :price, style: "display: block" %>
    <%= form.text_field :price, required: true %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/properties/_property.html.erb
<div id="<%= dom_id property %>">
<div class="card">
  <%# <img src="..." class="card-img-top" alt="..."> %>
  <div class="card-body">
    <h5 class="card-title">
      <%= property.type_property.name %> en <%= property.type_offer.name %>
    </h5>
    <p class="card-text"><%= property.description %></p>
    <p>
      <strong>Contacto:</strong>
      <%= property.user.name %><br>
      <a href="mailto:<%= property.user.email %>"><%= property.user.email %></a><br>
      <a href="tel:+<%= property.user.phone %>"><%= property.user.phone %></a>
    </p>
    <p>
      <strong>Features:</strong>
      <% property.features.each do |item| %>
        <%= content_tag :span, item.name, class: "tag"  %>
      <% end %>
    </p>

    <p>
      <strong>Area:</strong>
      <%= property.area %>
    </p>

    <p>
      <strong>Price:</strong>
      <%= property.price %>
    </p>
  </div>
</div>



</div>

app/views/properties/edit.html.erb
<h1>Editing property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Show this property", @property %> |
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/index.html.erb
<p style="color: green"><%= notice %></p>
<%= link_to "New property", new_property_path %>

<h1>Properties</h1>

<div id="properties">
  <% @properties.each do |property| %>
    <%= render property %>
    <p>
      <%= link_to "Show this property", property %>
    </p>
  <% end %>
</div>

<%== pagy_bootstrap_nav(@pagy) %>

app/views/properties/new.html.erb
<h1>New property</h1>

<%= render "form", property: @property %>

<br>

<div>
  <%= link_to "Back to properties", properties_path %>
</div>

app/views/properties/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @property %>

<div>
  <%= link_to "Edit this property", edit_property_path(@property) %> |
  <%= link_to "Back to properties", properties_path %>

  <%= button_to "Destroy this property", @property, method: :delete %>
</div>